

stages:
  - build

jobs:
  include:
    - stage: build
      os: windows
      language: csharp
      mono: none
      dotnet: none
      script:
        - choco install dotnetcore-sdk
        - cd Upm-Git
        - dotnet publish -c release
    - stage: build
      os:
        - osx
        - linux
      dist: xenial
      language: csharp
      mono: none
      dotnet: 2.2.300
      addons:
        apt:
          packages:
          - clang-3.9
      script:
        - cd Upm-Git
        - dotnet publish -c release
  