language: csharp
mono: none
script:
  - cd Upm-Git
  - dotnet restore
  - dotnet publish -c release
dist: xenial

jobs:
  include:
    - stage: build
      os: windows
  include:
    - stage: build
      dotnet: 2.2.300
      os:
        - linux
        - osx
  