version: 1.0.{build}
image: Visual Studio 2019
build_script:
- ps: >-
    git submodule update --init --recursive 2>&1

    cd Upm-Git

    dotnet publish -c release -r win-x64

    dotnet publish -c release -r linux-x64
