version: 1.0.{build}

image:
- Visual Studio 2017
- Ubuntu1804

for:
-
  matrix:
    only:
      - image: Ubuntu1804
  environment:
    rid: linux-x64
  before_build:
    pwsh: sudo apt-get install clang-3.9
  after_build:
    pwsh: Push-AppveyorArtifact Upm-Git\bin\release\netcoreapp2.2\linux-x64\native\UpmGit
-
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    rid: win-x64
  after_build:
    pwsh: Push-AppveyorArtifact Upm-Git\bin\release\netcoreapp2.2\win-x64\native\UpmGit.exe

build_script:
- pwsh: >-
    $env:GIT_REDIRECT_STDERR = '2>&1'

    git submodule update --init --recursive

    cd Upm-Git

    dotnet publish -c release -r $env:rid
