# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      runtimeId: "linux-x64"
    mac:
      imageName: "macos-latest"
      runtimeId: "osx-x64"
    windows:
      imageName: "windows-latest"
      runtimeId: "win-x64"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'
  GIT_REDIRECT_STDERR: '2>&1'

steps:
- script: sudo apt-get install clang-3.9
  displayName: Install dependencies
  condition: eq(variables.runtimeId, 'linux-x64')
- script: git submodule update --init --recursive
  displayName: Checkout submodules
- script: dotnet publish -c $(buildConfiguration) -r $(runtimeId) Upm-Git/UpmGit.csproj
  displayName: dotnet publish
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'Upm-Git/bin/release/$(runtimeId)/native'
    artifactName: Upm-Git