# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      runtimeId: "linux-x64"
    mac:
      imageName: "macos-latest"
      runtimeId: "osx-x64"
    windows:
      imageName: "windows-latest"
      runtimeId: "win-x64"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  project: 'Upm-Git'
  outputFramework: 'netcoreapp2.2'
  buildConfiguration: 'Release'
  GIT_REDIRECT_STDERR: '2>&1'

steps:
- script: git submodule update --init --recursive
  displayName: Checkout submodules
- script: sudo apt-get update && sudo apt-get -y install clang-3.9 libcurl4-openssl-dev zlib1g-dev libkrb5-dev
  displayName: Install dependencies
  condition: eq(variables.runtimeId, 'linux-x64')
- script: dotnet publish -c $(buildConfiguration) -r $(runtimeId) $(project)
  displayName: Compile
- script: "./$(project)/bin/$(buildConfiguration)/$(outputFramework)/$(runtimeId)/native/UpmGit" --test
  displayName: Test
- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathtoPublish: '$(project)/bin/$(buildConfiguration)/$(outputFramework)/$(runtimeId)/native'
    artifactName: '$(project)_$(runtimeId)'